name: pro
description: A starting point for Dart Process Api package, for Using commondline app to Easyly access start stop restart commands, see demo or examples.
version: 0.0.2
homepage: https://gitee.com/darto/pro

## pub publish --server=https://pub.dartlang.org

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  process_run: ^0.10.12+3
  alm: ^0.0.3
#    git: https://gitee.com/darto/alm.git
#    path: ../alm
